builds:
  - main: ./cmd/minesweeper/main.go
    id: minesweeper
    binary: minesweeper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: "6"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "windows" }}{{ .Arch }}.exe{{ end }}
      {{- else }}{{- title .Os }}{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: binary
checksum:
  name_template: "checksums.txt"
changelog:
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: "Other"
      order: 999
release:
  prerelease: auto
  mode: append
